package com.lmsuniversity.seed;

import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

/**
 * Years 3-4 specialization curriculum (16 courses each: [0..7] study year 3,
 * [8..15] study year 4) for every study program offered by each faculty.
 */
public final class ProgramCatalog {

	private ProgramCatalog() {
	}

	public record ProgramEntry(String name, List<CourseSpec> specialization) {
	}

	private static ProgramEntry entry(String name, String... courses) {
		if (courses.length != 16) {
			throw new IllegalStateException("Program " + name + " must have exactly 16 specialization courses, got " + courses.length);
		}
		return new ProgramEntry(name, Stream.of(courses).map(CourseSpec::of).toList());
	}

	private static final List<ProgramEntry> CS_PROGRAMS = List.of(
			entry("Computer Science",
					"Algorithms and Complexity Theory|7", "Computer Graphics|6", "Compiler Construction|6", "Distributed Systems|6",
					"Theory of Computation|6", "Functional Programming|5", "Database Systems II|6", "Human-Computer Interaction|5",
					"Machine Learning|7", "Parallel and High-Performance Computing|6", "Cloud Computing|6", "Advanced Algorithms|6",
					"Cryptography|5", "Research Methods in Computer Science|4", "Quantum Computing Fundamentals (Elective)|5", "Capstone Project in Computer Science|8"),
			entry("Software Engineering",
					"Software Architecture and Design Patterns|7", "Software Testing and Quality Assurance|6", "Agile Project Management|5", "Mobile Application Development|6",
					"Database Systems II|6", "Requirements Engineering|5", "Web Application Development|6", "DevOps and Continuous Integration|6",
					"Enterprise Software Development|6", "Cloud-Native Application Development|6", "Software Maintenance and Refactoring|5", "Microservices Architecture|6",
					"Secure Software Development|6", "Software Project Management|5", "UX Engineering (Elective)|5", "Capstone Project in Software Engineering|8"),
			entry("Information Systems",
					"Enterprise Resource Planning Systems|6", "Business Process Modeling|5", "Data Warehousing|6", "Systems Analysis and Design|6",
					"IT Project Management|5", "Database Administration|6", "Information Systems Security|6", "Decision Support Systems|5",
					"Business Intelligence|6", "Enterprise Architecture|6", "IT Governance and Compliance|5", "Knowledge Management Systems|5",
					"E-Business Systems|5", "Information Systems Auditing|5", "ERP Implementation Practicum (Elective)|6", "Capstone Project in Information Systems|8"),
			entry("Data Science and Analytics",
					"Statistical Learning|7", "Data Mining|6", "Big Data Technologies|6", "Data Visualization|5",
					"Applied Linear Algebra for Data Science|5", "Database Systems II|6", "Exploratory Data Analysis|5", "Time Series Analysis|6",
					"Machine Learning|7", "Deep Learning|6", "Natural Language Processing|6", "Data Engineering Pipelines|6",
					"Business Analytics|5", "Ethics in Data Science|4", "Reinforcement Learning (Elective)|5", "Capstone Project in Data Science|8"),
			entry("Cybersecurity",
					"Network Security|6", "Cryptography|6", "Operating Systems Security|6", "Secure Software Development|6",
					"Ethical Hacking and Penetration Testing|6", "Digital Forensics|5", "Risk Management and Compliance|5", "Web Application Security|5",
					"Malware Analysis|6", "Cloud Security|6", "Security Operations and Incident Response|6", "Applied Cryptanalysis|5",
					"Cyber Law and Ethics|4", "Security Architecture Design|5", "IoT Security (Elective)|5", "Capstone Project in Cybersecurity|8"),
			entry("Artificial Intelligence and Machine Learning",
					"Machine Learning Foundations|7", "Neural Networks|6", "Knowledge Representation and Reasoning|6", "Search and Optimization Algorithms|6",
					"Probabilistic Graphical Models|6", "Database Systems II|6", "Computer Vision|6", "Robotics Fundamentals|5",
					"Deep Learning|7", "Natural Language Processing|6", "Reinforcement Learning|6", "AI Ethics and Society|4",
					"Generative Models|6", "Multi-Agent Systems|5", "Explainable AI (Elective)|5", "Capstone Project in Artificial Intelligence|8"),
			entry("Computer Engineering",
					"Embedded Systems|6", "Microprocessor Systems|6", "Digital Signal Processing|6", "Computer Networks II|6",
					"VLSI Design Fundamentals|6", "Real-Time Operating Systems|6", "Hardware Description Languages|5", "Sensors and Actuators|5",
					"Internet of Things Systems|6", "FPGA-Based Design|6", "Robotics and Automation|6", "System-on-Chip Design|5",
					"Hardware-Software Co-design|5", "Computer Engineering Project Management|4", "Wireless Embedded Systems (Elective)|5", "Capstone Project in Computer Engineering|8"),
			entry("Information Technology Management",
					"IT Service Management|6", "Business Process Modeling|5", "IT Project Management|6", "Enterprise Resource Planning Systems|6",
					"Information Systems Security|6", "IT Procurement and Vendor Management|5", "Database Administration|6", "Digital Transformation Strategy|5",
					"IT Governance and Compliance|6", "Business Intelligence|6", "Change Management for IT Projects|5", "IT Risk Management|5",
					"Strategic IT Planning|5", "Innovation Management in IT|5", "Agile Leadership (Elective)|5", "Capstone Project in IT Management|8"));

	private static final List<ProgramEntry> EE_PROGRAMS = List.of(
			entry("Power Engineering",
					"Power Systems Analysis|7", "Electrical Machines|6", "High Voltage Engineering|6", "Power Electronics|6",
					"Electric Power Generation|6", "Control Systems|6", "Electromagnetic Fields|5", "Protection and Relaying|5",
					"Power System Stability and Control|6", "Renewable Energy Integration|6", "Smart Grid Technologies|6", "Electrical Power Distribution|5",
					"Energy Economics|4", "Industrial Power Applications|5", "High-Voltage Direct Current Transmission (Elective)|5", "Capstone Project in Power Engineering|8"),
			entry("Electronics Engineering",
					"Analog Electronics|7", "Digital Electronics Design|6", "Microprocessor Systems|6", "Control Systems|6",
					"Electromagnetic Fields|5", "Sensors and Instrumentation|6", "Power Electronics|6", "Electronic Devices and Circuits II|5",
					"VLSI Design Fundamentals|6", "Embedded Systems Design|6", "Analog Integrated Circuit Design|6", "Digital Signal Processing|6",
					"RF and Microwave Electronics|5", "Electronics Manufacturing Technology|4", "Photonics and Optoelectronics (Elective)|5", "Capstone Project in Electronics Engineering|8"),
			entry("Telecommunications Engineering",
					"Communication Systems I|7", "Digital Signal Processing|6", "Antenna Theory and Design|6", "Microwave Engineering|6",
					"Electromagnetic Fields|5", "Data Communication Networks|6", "Probability for Communication Systems|5", "Analog Electronics|5",
					"Communication Systems II|6", "Optical Communication Networks|6", "Mobile and Wireless Networks|6", "Satellite Communication Systems|5",
					"Network Security for Telecommunications|5", "Telecommunications Regulation and Policy|4", "5G Network Architecture (Elective)|5", "Capstone Project in Telecommunications Engineering|8"),
			entry("Automation and Control Engineering",
					"Control Systems|7", "Industrial Automation|6", "Programmable Logic Controllers|6", "Sensors and Instrumentation|6",
					"Microprocessor Systems|6", "Robotics Fundamentals|5", "System Modeling and Simulation|5", "Power Electronics|5",
					"Advanced Control Systems|6", "Robotics and Automation|6", "SCADA Systems|6", "Mechatronic Systems Design|5",
					"Process Control Engineering|5", "Industrial Communication Networks|4", "Autonomous Systems (Elective)|5", "Capstone Project in Automation Engineering|8"),
			entry("Renewable Energy Systems",
					"Solar Energy Systems|7", "Wind Energy Systems|6", "Energy Storage Technologies|6", "Power Electronics|6",
					"Electrical Machines|6", "Sustainable Energy Policy|5", "Thermodynamics for Energy Systems|5", "Electromagnetic Fields|5",
					"Smart Grid Technologies|6", "Renewable Energy Integration|6", "Hydropower and Geothermal Systems|5", "Energy Efficiency and Auditing|5",
					"Energy Economics|4", "Microgrid Design|5", "Hydrogen and Fuel Cell Technologies (Elective)|5", "Capstone Project in Renewable Energy Systems|8"),
			entry("Biomedical Engineering",
					"Human Physiology for Engineers|6", "Biomedical Instrumentation|6", "Medical Imaging Systems|6", "Biomaterials|5",
					"Signal Processing for Biomedical Applications|6", "Sensors and Instrumentation|5", "Control Systems|6", "Anatomy for Engineers|5",
					"Medical Device Design|6", "Rehabilitation Engineering|5", "Bioinformatics|5", "Clinical Engineering and Hospital Technology|5",
					"Regulatory Affairs in Medical Devices|4", "Neural Engineering|5", "Tissue Engineering (Elective)|5", "Capstone Project in Biomedical Engineering|8"),
			entry("Microelectronics",
					"Semiconductor Devices|7", "VLSI Design Fundamentals|6", "Analog Integrated Circuit Design|6", "Digital Integrated Circuit Design|6",
					"Microfabrication Technology|6", "Electromagnetic Fields|5", "Microprocessor Systems|6", "Solid State Physics|5",
					"System-on-Chip Design|6", "Mixed-Signal Circuit Design|6", "Nanoelectronics|5", "Semiconductor Device Fabrication Lab|5",
					"Reliability and Testing of Integrated Circuits|4", "IC Packaging Technology|5", "MEMS Design (Elective)|5", "Capstone Project in Microelectronics|8"));

	private static final List<ProgramEntry> ME_PROGRAMS = List.of(
			entry("Mechanical Engineering",
					"Machine Design I|7", "Thermodynamics II|6", "Heat Transfer|6", "Kinematics and Dynamics of Machinery|6",
					"Manufacturing Processes II|6", "Hydraulics and Pneumatics|5", "Mechanical Vibrations|5", "Computer-Aided Engineering|5",
					"Machine Design II|6", "CNC Machining and Automation|6", "Maintenance Engineering|5", "Finite Element Analysis|6",
					"Mechanical Systems Design Project|5", "Quality Engineering|4", "Robotics for Mechanical Engineers (Elective)|5", "Capstone Project in Mechanical Engineering|8"),
			entry("Industrial Engineering and Management",
					"Operations Management|6", "Production Planning and Control|6", "Industrial Ergonomics|5", "Quality Management Systems|6",
					"Supply Chain Management|6", "Facility Layout and Design|5", "Engineering Economics|5", "Manufacturing Processes II|6",
					"Lean Manufacturing|6", "Project Management for Engineers|5", "Logistics and Distribution Management|5", "Simulation of Production Systems|5",
					"Six Sigma and Process Improvement|5", "Industrial Safety Management|4", "Enterprise Resource Planning for Manufacturing (Elective)|5", "Capstone Project in Industrial Engineering|8"),
			entry("Mechatronics",
					"Mechatronic Systems Design|7", "Sensors and Actuators|6", "Programmable Logic Controllers|6", "Control Systems|6",
					"Microprocessor Systems|6", "Hydraulics and Pneumatics|5", "Computer-Aided Engineering|5", "Kinematics and Dynamics of Machinery|5",
					"Robotics and Automation|6", "Embedded Systems for Mechatronics|6", "Industrial Robotics|6", "Machine Vision Systems|5",
					"Motion Control Systems|4", "Mechatronic Product Design|5", "Autonomous Mobile Robots (Elective)|5", "Capstone Project in Mechatronics|8"),
			entry("Automotive Engineering",
					"Internal Combustion Engines|7", "Vehicle Dynamics|6", "Automotive Materials|5", "Automotive Electronics|6",
					"Manufacturing Processes II|6", "Hydraulics and Pneumatics|5", "Thermodynamics II|6", "Mechanical Vibrations|5",
					"Vehicle Design and Safety Engineering|6", "Electric and Hybrid Vehicle Technology|6", "Automotive Transmission Systems|5", "Vehicle Emissions and Environmental Control|5",
					"Automotive Quality Engineering|4", "Advanced Driver Assistance Systems|5", "Motorsport Engineering (Elective)|5", "Capstone Project in Automotive Engineering|8"),
			entry("Energy Engineering",
					"Thermodynamics II|7", "Heat Transfer|6", "Fluid Machinery|6", "Power Plant Engineering|6",
					"Energy Conversion Systems|6", "Hydraulics and Pneumatics|5", "Combustion Engineering|5", "Engineering Economics|5",
					"Renewable Energy Technologies|6", "Energy Efficiency and Auditing|6", "Cogeneration Systems|5", "HVAC Systems Design|5",
					"Energy Storage Technologies|4", "Environmental Impact of Energy Systems|5", "Nuclear Energy Fundamentals (Elective)|5", "Capstone Project in Energy Engineering|8"),
			entry("Materials Engineering",
					"Mechanical Behavior of Materials|7", "Materials Characterization Techniques|6", "Polymer Engineering|5", "Ceramic Materials|5",
					"Metallurgy and Heat Treatment|6", "Composite Materials|6", "Corrosion Science|5", "Manufacturing Processes II|6",
					"Nanomaterials|5", "Materials Selection and Design|6", "Failure Analysis of Materials|5", "Surface Engineering and Coatings|5",
					"Sustainable Materials and Recycling|4", "Materials Testing Laboratory|5", "Biomaterials for Engineers (Elective)|5", "Capstone Project in Materials Engineering|8"),
			entry("Aerospace Engineering",
					"Aerodynamics|7", "Flight Mechanics|6", "Aircraft Structures|6", "Propulsion Systems|6",
					"Aerospace Materials|5", "Avionics Systems|5", "Computer-Aided Engineering|5", "Mechanical Vibrations|5",
					"Spacecraft Systems Engineering|6", "Aircraft Design|6", "Flight Control Systems|5", "Aerospace Manufacturing Technology|5",
					"Orbital Mechanics|5", "Aviation Safety and Regulation|4", "Unmanned Aerial Systems (Elective)|5", "Capstone Project in Aerospace Engineering|8"));

	private static final List<ProgramEntry> CIV_PROGRAMS = List.of(
			entry("Civil Engineering",
					"Structural Analysis II|7", "Reinforced Concrete Structures|6", "Geotechnical Engineering|6", "Transportation Engineering|6",
					"Hydraulics and Hydrology|6", "Construction Management Fundamentals|5", "Steel Structures|5", "Building Services Engineering|5",
					"Foundation Engineering|6", "Bridge Engineering|6", "Earthquake Engineering|5", "Water Supply and Sewerage Systems|5",
					"Construction Contract Law|4", "Infrastructure Project Planning|5", "Sustainable Construction (Elective)|5", "Capstone Project in Civil Engineering|8"),
			entry("Architecture",
					"Architectural Design Studio I|8", "Building Construction Technology|6", "Architectural Theory|5", "Urban Design Principles|5",
					"Structural Systems for Architects|6", "Environmental Design and Sustainability|5", "Building Information Modeling|5", "History of Modern Architecture|5",
					"Architectural Design Studio II|8", "Landscape Architecture|5", "Interior Architecture|5", "Architectural Acoustics and Lighting|4",
					"Heritage Conservation|4", "Urban Housing Design|5", "Parametric Design (Elective)|5", "Capstone Project in Architecture|8"),
			entry("Urban Planning",
					"Urban Design Principles|6", "Land Use Planning|6", "Transportation Planning|6", "Urban Infrastructure Systems|6",
					"Geographic Information Systems|6", "Housing Policy|5", "Environmental Planning|5", "Urban Sociology|5",
					"Regional Planning|5", "Smart Cities and Technology|5", "Urban Renewal and Heritage|5", "Participatory Planning Methods|5",
					"Urban Planning Law|4", "Sustainable Urban Mobility|5", "Climate-Resilient Urban Design (Elective)|5", "Capstone Project in Urban Planning|8"),
			entry("Structural Engineering",
					"Structural Analysis II|7", "Reinforced Concrete Structures|6", "Steel Structures|6", "Structural Dynamics|6",
					"Finite Element Methods in Structural Engineering|6", "Geotechnical Engineering|6", "Prestressed Concrete|5", "Building Services Engineering|5",
					"Earthquake Engineering|6", "Bridge Engineering|6", "Advanced Structural Design|5", "Structural Health Monitoring|5",
					"Wind Engineering for Structures|4", "Foundation Engineering|5", "Timber Structures (Elective)|5", "Capstone Project in Structural Engineering|8"),
			entry("Geodesy and Geoinformatics",
					"Geodetic Surveying|6", "Geographic Information Systems|6", "Photogrammetry and Remote Sensing|6", "Cartography|5",
					"Satellite Positioning Systems|6", "Cadastre and Land Administration|5", "Spatial Data Analysis|6", "Engineering Surveying|5",
					"Geoinformation Systems Design|5", "Digital Terrain Modeling|5", "Geodetic Network Adjustment|5", "Spatial Database Management|5",
					"Remote Sensing Applications|4", "Geospatial Web Services|5", "UAV-Based Mapping (Elective)|5", "Capstone Project in Geodesy and Geoinformatics|8"),
			entry("Environmental Engineering",
					"Water and Wastewater Treatment|7", "Air Quality Engineering|6", "Solid Waste Management|6", "Environmental Chemistry|6",
					"Hydrology and Water Resources|6", "Environmental Impact Assessment|5", "Environmental Microbiology|5", "Soil and Groundwater Remediation|5",
					"Climate Change Mitigation Engineering|6", "Industrial Wastewater Treatment|5", "Environmental Monitoring and Sensing|5", "Renewable Resource Management|5",
					"Environmental Law and Policy|4", "Sustainable Waste-to-Energy Systems|5", "Life Cycle Assessment (Elective)|5", "Capstone Project in Environmental Engineering|8"),
			entry("Construction Management",
					"Construction Planning and Scheduling|6", "Construction Cost Estimation|6", "Construction Materials and Methods|6", "Building Information Modeling|6",
					"Construction Contract Law|5", "Construction Equipment Management|5", "Construction Safety Management|6", "Construction Quality Control|5",
					"Construction Project Risk Management|5", "Real Estate Development|5", "Construction Procurement and Tendering|5", "Lean Construction|5",
					"Facilities Management|4", "Sustainable Construction Practices|5", "Construction Dispute Resolution (Elective)|5", "Capstone Project in Construction Management|8"));

	private static final List<ProgramEntry> ECO_PROGRAMS = List.of(
			entry("Economics",
					"Econometrics I|7", "Microeconomic Theory|6", "Macroeconomic Theory|6", "Public Economics|5",
					"Monetary Economics|5", "International Economics|6", "Economic Development|5", "Game Theory|5",
					"Econometrics II|6", "Labor Economics|5", "Economic Policy Analysis|5", "Behavioral Economics|5",
					"Environmental Economics|4", "History of Economic Thought|5", "Economics of Innovation (Elective)|5", "Capstone Project in Economics|8"),
			entry("Business Administration",
					"Strategic Management|6", "Organizational Behavior|6", "Operations Management|6", "Human Resource Management|6",
					"Business Finance|6", "Management Information Systems|5", "Business Ethics and Corporate Governance|5", "Negotiation and Conflict Management|5",
					"Entrepreneurship and New Venture Creation|5", "Change Management|5", "Business Analytics|5", "International Business Strategy|5",
					"Leadership Development|4", "Business Law and Contracts|5", "Family Business Management (Elective)|5", "Capstone Project in Business Administration|8"),
			entry("Finance and Banking",
					"Corporate Finance|7", "Money and Banking|6", "Financial Markets and Institutions|6", "Investment Analysis|6",
					"Financial Accounting II|5", "Risk Management in Finance|6", "Financial Statement Analysis|5", "Quantitative Finance Methods|5",
					"Portfolio Management|6", "International Finance|5", "Bank Management|5", "Derivatives and Risk Hedging|5",
					"Central Banking and Monetary Policy|4", "Fintech and Digital Banking|5", "Behavioral Finance (Elective)|5", "Capstone Project in Finance|8"),
			entry("Accounting and Auditing",
					"Financial Accounting II|7", "Cost and Managerial Accounting|6", "Auditing Principles|6", "Taxation|6",
					"Corporate Finance|5", "Accounting Information Systems|6", "Financial Statement Analysis|5", "Business Law and Contracts|5",
					"Advanced Auditing|6", "International Financial Reporting Standards|5", "Forensic Accounting|5", "Tax Planning and Compliance|5",
					"Internal Control and Risk Assessment|4", "Public Sector Accounting|5", "Sustainability Accounting (Elective)|5", "Capstone Project in Accounting and Auditing|8"),
			entry("Marketing",
					"Consumer Behavior|6", "Marketing Research|6", "Brand Management|6", "Digital Marketing|6",
					"Marketing Strategy|6", "Advertising and Promotion|5", "Retail Management|5", "Services Marketing|5",
					"Marketing Analytics|5", "International Marketing|5", "Social Media and Content Marketing|5", "Product Management|5",
					"Sales Management|4", "Marketing Ethics and Consumer Protection|5", "Marketing for Startups (Elective)|5", "Capstone Project in Marketing|8"),
			entry("International Business",
					"International Trade Theory and Policy|6", "Cross-Cultural Management|6", "Global Supply Chain Management|6", "International Marketing|6",
					"International Finance|6", "Export-Import Management|5", "Comparative Economic Systems|5", "Business Communication in Global Markets|5",
					"Global Business Strategy|5", "International Business Law|5", "Emerging Markets and Globalization|5", "Multinational Corporate Management|5",
					"Trade Finance and Documentation|4", "International Negotiation|5", "Doing Business in the European Union (Elective)|5", "Capstone Project in International Business|8"),
			entry("Management",
					"Principles of Strategic Management|6", "Organizational Design and Theory|6", "Human Resource Management|6", "Operations and Supply Chain Management|6",
					"Managerial Decision Making|6", "Project Management|5", "Business Communication|5", "Corporate Governance|5",
					"Leadership and Team Management|5", "Innovation and Knowledge Management|5", "Performance Management|5", "Crisis and Risk Management|5",
					"Business Ethics|4", "Management Consulting Practicum|5", "Digital Transformation Management (Elective)|5", "Capstone Project in Management|8"),
			entry("Tourism and Hospitality Management",
					"Tourism Economics|6", "Hospitality Operations Management|6", "Destination Marketing|6", "Event Management|6",
					"Travel Agency and Tour Operations|5", "Hospitality Service Quality Management|6", "Tourism Geography|5", "Hotel Revenue Management|5",
					"Sustainable Tourism Development|5", "Cultural and Heritage Tourism|5", "Tourism Policy and Planning|5", "Food and Beverage Management|5",
					"Tourism Law and Regulation|4", "Digital Marketing for Hospitality|5", "Ecotourism Management (Elective)|5", "Capstone Project in Tourism and Hospitality Management|8"));

	private static final List<ProgramEntry> LAW_PROGRAMS = List.of(
			entry("General Law",
					"Civil Law II: Obligations|7", "Criminal Law II: Special Part|6", "Civil Procedure Law|6", "Commercial Law|6",
					"Inheritance Law|5", "Property Law|6", "Constitutional Litigation|5", "Legal Drafting|5",
					"Criminal Procedure Law|6", "Enforcement Procedure Law|5", "Notarial Law and Practice|5", "Bankruptcy and Insolvency Law|5",
					"Legal Ethics and Professional Responsibility|4", "Alternative Dispute Resolution|5", "Media and Information Law (Elective)|5", "Capstone Project in Law|8"),
			entry("International Law",
					"International Public Law II|7", "International Organizations Law|6", "Human Rights Law|6", "International Humanitarian Law|6",
					"Diplomatic and Consular Law|5", "Law of Treaties|6", "International Environmental Law|5", "International Criminal Law|5",
					"International Dispute Settlement|6", "Law of the Sea|5", "International Trade Law|5", "Refugee and Migration Law|5",
					"International Investment Law|4", "Comparative Constitutional Law|5", "Law of International Organizations Practicum (Elective)|5", "Capstone Project in International Law|8"),
			entry("Business Law",
					"Commercial Law|7", "Company Law|6", "Contract Law for Business|6", "Securities Regulation|6",
					"Competition Law|6", "Banking and Finance Law|5", "Intellectual Property Law|6", "Insurance Law|5",
					"Mergers and Acquisitions Law|6", "International Commercial Arbitration|5", "Bankruptcy and Insolvency Law|5", "Tax Law for Business|5",
					"Corporate Compliance and Governance|4", "E-Commerce Law|5", "Capital Markets Law (Elective)|5", "Capstone Project in Business Law|8"),
			entry("Criminal Law and Criminology",
					"Criminal Law II: Special Part|7", "Criminology|6", "Criminal Procedure Law|6", "Forensic Science for Lawyers|6",
					"Penology and Sentencing|5", "Juvenile Justice|6", "Victimology|5", "Comparative Criminal Justice Systems|5",
					"Organized Crime and Corruption|5", "Criminal Investigation Techniques|5", "International Criminal Law|5", "Cybercrime and Digital Evidence|5",
					"Restorative Justice|4", "Criminal Justice Policy|5", "White-Collar Crime (Elective)|5", "Capstone Project in Criminal Law and Criminology|8"),
			entry("European Union Law",
					"EU Institutional Law|7", "EU Single Market Law|6", "EU Competition Law|6", "EU Human Rights Protection|6",
					"EU External Relations Law|5", "EU Judicial Protection|6", "Comparative European Legal Systems|5", "EU Environmental Law|5",
					"EU Trade and Customs Law|5", "EU Migration and Asylum Law|5", "EU Financial Regulation|5", "EU Agricultural and Rural Policy Law|5",
					"EU Enlargement Policy|4", "EU Data Protection Law|5", "EU Energy Law (Elective)|5", "Capstone Project in European Union Law|8"),
			entry("Labor and Social Law",
					"Labor Law: Individual Employment Relations|7", "Labor Law: Collective Labor Relations|6", "Social Security Law|6", "Occupational Health and Safety Law|6",
					"Employment Discrimination Law|5", "Pension and Insurance Law|6", "Migration and Labor Mobility Law|5", "Public Sector Employment Law|5",
					"Labor Dispute Resolution|5", "International Labor Standards|5", "Social Welfare Policy and Law|5", "Trade Union Law|5",
					"Workplace Mediation|4", "Comparative Labor Systems|5", "Gig Economy and Labor Law (Elective)|5", "Capstone Project in Labor and Social Law|8"),
			entry("Public Administration Law",
					"Administrative Procedure Law|7", "Public Finance Law|6", "Local Self-Government Law|6", "Public Procurement Law|6",
					"Civil Service Law|5", "Regulatory Law and Policy|6", "Administrative Litigation|5", "Public Sector Ethics|5",
					"E-Government and Digital Administration|5", "Public Administration Reform|5", "State Aid and Public Subsidies Law|5", "Government Contracting|5",
					"Public Accountability and Anti-Corruption Law|4", "Comparative Public Administration|5", "Local Economic Development Law (Elective)|5", "Capstone Project in Public Administration Law|8"));

	private static final List<ProgramEntry> MED_PROGRAMS = List.of(
			entry("General Medicine",
					"Internal Medicine I|8", "General Surgery I|7", "Pathology|6", "Pharmacology|6",
					"Clinical Pharmacology|5", "Radiology Fundamentals|5", "Medical Ethics and Bioethics|5", "Epidemiology|5",
					"Internal Medicine II|7", "General Surgery II|6", "Pediatrics|6", "Obstetrics and Gynecology|6",
					"Psychiatry|5", "Emergency Medicine|5", "Geriatric Medicine (Elective)|5", "Capstone Clinical Practicum in Medicine|8"),
			entry("Dentistry",
					"Oral Anatomy and Histology|6", "Dental Materials Science|6", "Operative Dentistry|7", "Oral Pathology|6",
					"Periodontology|6", "Dental Radiology|5", "Local Anesthesia in Dentistry|5", "Preventive Dentistry|5",
					"Oral Surgery|6", "Prosthodontics|6", "Orthodontics|5", "Endodontics|5",
					"Pediatric Dentistry|5", "Dental Public Health|4", "Implantology Fundamentals (Elective)|5", "Capstone Clinical Practicum in Dentistry|8"),
			entry("Pharmacy",
					"Pharmaceutical Chemistry I|7", "Pharmaceutical Technology|6", "Pharmacognosy|6", "Pharmacology II|6",
					"Toxicology|6", "Pharmaceutical Analysis|5", "Biopharmaceutics|5", "Clinical Pharmacy Fundamentals|5",
					"Pharmaceutical Chemistry II|6", "Industrial Pharmacy|5", "Clinical Pharmacy Practice|6", "Pharmacoeconomics|5",
					"Pharmacy Law and Ethics|4", "Drug Information and Patient Counseling|5", "Herbal and Natural Medicine (Elective)|5", "Capstone Practicum in Pharmacy|8"),
			entry("Nursing",
					"Adult Health Nursing|7", "Pediatric Nursing|6", "Maternal and Newborn Nursing|6", "Pharmacology for Nurses|5",
					"Nursing Research Methods|5", "Mental Health Nursing|6", "Community Health Nursing|5", "Nursing Ethics and Law|5",
					"Critical Care Nursing|6", "Geriatric Nursing|5", "Perioperative Nursing|5", "Nursing Management and Leadership|5",
					"Emergency and Disaster Nursing|4", "Palliative and End-of-Life Care|5", "Oncology Nursing (Elective)|5", "Capstone Clinical Practicum in Nursing|8"),
			entry("Physiotherapy",
					"Kinesiology and Biomechanics|6", "Therapeutic Exercise|6", "Musculoskeletal Physiotherapy|7", "Electrotherapy and Physical Agents|5",
					"Neurological Physiotherapy|6", "Cardiopulmonary Physiotherapy|6", "Manual Therapy Techniques|5", "Clinical Assessment in Physiotherapy|5",
					"Sports Physiotherapy|5", "Pediatric Physiotherapy|5", "Geriatric Physiotherapy|5", "Rehabilitation Engineering and Assistive Devices|5",
					"Physiotherapy Practice Management|4", "Occupational Health Physiotherapy|5", "Aquatic Therapy (Elective)|5", "Capstone Clinical Practicum in Physiotherapy|8"),
			entry("Medical Laboratory Diagnostics",
					"Clinical Chemistry|7", "Hematology|6", "Medical Microbiology Diagnostics|6", "Immunohematology and Blood Banking|6",
					"Histopathology Techniques|5", "Laboratory Quality Management|5", "Clinical Parasitology|5", "Molecular Diagnostics Fundamentals|5",
					"Clinical Microbiology Advanced Methods|5", "Cytology and Cytogenetics|5", "Laboratory Automation|5", "Toxicology Testing|5",
					"Laboratory Safety and Biosafety|4", "Point-of-Care Testing|5", "Molecular Genetics Diagnostics (Elective)|5", "Capstone Practicum in Medical Laboratory Diagnostics|8"),
			entry("Public Health",
					"Epidemiology II|6", "Biostatistics for Public Health|6", "Health Promotion and Education|6", "Environmental and Occupational Health|6",
					"Health Policy and Systems|6", "Global Health|5", "Maternal and Child Health|5", "Health Economics|5",
					"Disease Prevention and Control|5", "Health Program Planning and Evaluation|5", "Nutrition and Public Health|5", "Health Informatics|5",
					"Public Health Law and Ethics|4", "Disaster and Emergency Public Health|5", "One Health and Zoonotic Diseases (Elective)|5", "Capstone Project in Public Health|8"),
			entry("Radiology Technology",
					"Radiographic Imaging Techniques|7", "Radiation Physics and Safety|6", "Cross-Sectional Anatomy for Imaging|6", "Computed Tomography Technology|6",
					"Magnetic Resonance Imaging Technology|6", "Contrast Media and Pharmacology|5", "Digital Image Processing in Radiology|5", "Patient Care in Radiologic Technology|5",
					"Nuclear Medicine Technology|5", "Mammography and Breast Imaging|5", "Interventional Radiology Techniques|5", "Radiation Therapy Fundamentals|5",
					"Quality Assurance in Medical Imaging|4", "Ultrasound Imaging Technology|5", "Pediatric Radiologic Technology (Elective)|5", "Capstone Practicum in Radiology Technology|8"));

	private static final List<ProgramEntry> HUM_PROGRAMS = List.of(
			entry("Psychology",
					"Cognitive Psychology|7", "Personality Psychology|6", "Social Psychology|6", "Psychological Assessment and Testing|6",
					"Abnormal Psychology|6", "Research Methods in Psychology|5", "Neuropsychology|5", "Health Psychology|5",
					"Clinical Psychology|6", "Counseling Psychology|5", "Organizational Psychology|5", "Psychotherapy Foundations|5",
					"Forensic Psychology|4", "Educational Psychology|5", "Psychology of Trauma (Elective)|5", "Capstone Project in Psychology|8"),
			entry("Sociology",
					"Sociological Theory II|6", "Sociology of Education|6", "Sociology of the Family|6", "Quantitative Research Methods in Sociology|6",
					"Qualitative Research Methods in Sociology|6", "Political Sociology|5", "Urban Sociology|5", "Sociology of Religion|5",
					"Sociology of Gender|5", "Sociology of Migration|5", "Social Stratification and Inequality|5", "Sociology of Work|5",
					"Environmental Sociology|4", "Social Policy Analysis|5", "Digital Society and New Media (Elective)|5", "Capstone Project in Sociology|8"),
			entry("History",
					"National History I|6", "European History I: Early Modern Period|6", "Historiography and Historical Methods|6", "History of Southeastern Europe|6",
					"Economic History|6", "Archival Studies|5", "Ancient Civilizations|5", "History of Diplomacy|5",
					"National History II|6", "European History II: 19th and 20th Century|6", "History of the Cold War|5", "Cultural and Social History|5",
					"History of Religion|4", "Oral History Methods|5", "Microhistory Practicum (Elective)|5", "Capstone Project in History|8"),
			entry("English Language and Literature",
					"English Syntax|6", "British Literature I|6", "American Literature|6", "Translation Theory and Practice|6",
					"Sociolinguistics|6", "English Phonetics and Phonology|5", "Literary Theory and Criticism|5", "Academic English for Specific Purposes|5",
					"British Literature II|5", "Postcolonial Literature|5", "English Language Teaching Methodology|5", "Discourse Analysis|5",
					"Comparative Literature|4", "Shakespeare Studies|5", "Creative Writing in English (Elective)|5", "Capstone Project in English Language and Literature|8"),
			entry("Pedagogy",
					"Curriculum Theory and Design|6", "Educational Psychology|6", "Comparative Education Systems|6", "Inclusive Education|6",
					"Methodology of Teaching|6", "Educational Assessment and Evaluation|5", "History of Education|5", "Family and Community Education|5",
					"Special Education Needs|5", "Early Childhood Education|5", "Adult and Lifelong Learning|5", "Educational Technology|5",
					"School Management and Leadership|4", "Pedagogical Practicum|5", "Career Guidance and Counseling (Elective)|5", "Capstone Project in Pedagogy|8"),
			entry("Philosophy",
					"Epistemology|6", "Philosophy of Science|6", "Political Philosophy|6", "Philosophy of Mind|6",
					"Aesthetics|6", "Metaphysics|5", "History of Ancient Philosophy|5", "Philosophical Logic|5",
					"Philosophy of Language|5", "Contemporary Continental Philosophy|5", "Bioethics|5", "Philosophy of Religion|5",
					"Existentialism|4", "Philosophy of Law|5", "Eastern Philosophy (Elective)|5", "Capstone Project in Philosophy|8"),
			entry("Journalism and Communication Studies",
					"News Writing and Reporting|6", "Media Law and Ethics|6", "Broadcast Journalism|6", "Public Relations Fundamentals|6",
					"Digital Journalism|6", "Investigative Journalism|5", "Media Theory|5", "Photojournalism|5",
					"Political Communication|5", "Crisis Communication|5", "Data Journalism|5", "Documentary Production|5",
					"Media Management and Economics|4", "Social Media Strategy|5", "International Journalism (Elective)|5", "Capstone Project in Journalism and Communication Studies|8"));

	private static final List<ProgramEntry> SCI_PROGRAMS = List.of(
			entry("Mathematics",
					"Real Analysis|7", "Abstract Algebra|6", "Numerical Analysis|6", "Topology|6",
					"Complex Analysis|6", "Probability Theory II|5", "Mathematical Statistics|5", "Discrete Mathematics II|5",
					"Functional Analysis|6", "Differential Geometry|5", "Mathematical Modeling|5", "Number Theory|5",
					"History of Mathematics|4", "Operations Research|5", "Graph Theory (Elective)|5", "Capstone Project in Mathematics|8"),
			entry("Physics",
					"Classical Mechanics|7", "Electrodynamics|6", "Quantum Mechanics I|6", "Thermodynamics and Statistical Physics|6",
					"Mathematical Methods for Physics|6", "Optics|5", "Atomic and Molecular Physics|5", "Experimental Physics Lab II|5",
					"Quantum Mechanics II|6", "Solid State Physics|5", "Nuclear and Particle Physics|5", "Astrophysics|5",
					"Computational Physics|4", "Condensed Matter Physics|5", "Plasma Physics (Elective)|5", "Capstone Project in Physics|8"),
			entry("Chemistry",
					"Physical Chemistry I|7", "Analytical Chemistry|6", "Inorganic Chemistry II|6", "Organic Chemistry II|6",
					"Instrumental Analysis|6", "Spectroscopy|5", "Chemical Thermodynamics|5", "Chemical Laboratory Safety and Techniques|5",
					"Physical Chemistry II|6", "Polymer Chemistry|5", "Environmental Chemistry|5", "Industrial Chemistry|5",
					"Computational Chemistry|4", "Chemical Kinetics|5", "Medicinal Chemistry (Elective)|5", "Capstone Project in Chemistry|8"),
			entry("Biology",
					"Genetics|7", "Microbiology|6", "Plant Physiology|6", "Animal Physiology|6",
					"Ecology|6", "Evolutionary Biology|5", "Molecular Biology|5", "Biostatistics|5",
					"Molecular Genetics|6", "Conservation Biology|5", "Marine Biology|5", "Developmental Biology|5",
					"Bioinformatics for Biologists|4", "Immunology|5", "Entomology (Elective)|5", "Capstone Project in Biology|8"),
			entry("Environmental Science",
					"Environmental Chemistry|7", "Ecology|6", "Climatology|6", "Pollution Control and Remediation|6",
					"Environmental Impact Assessment|6", "Natural Resource Management|5", "Soil Science|5", "Environmental Monitoring Techniques|5",
					"Climate Change Science|6", "Conservation and Biodiversity|5", "Sustainable Development Practices|5", "Environmental Policy and Law|5",
					"Renewable Resource Management|4", "Waste Management Science|5", "Marine and Coastal Ecosystems (Elective)|5", "Capstone Project in Environmental Science|8"),
			entry("Geography",
					"Physical Geography|6", "Human Geography|6", "Cartography and GIS|6", "Climatology|6",
					"Geomorphology|6", "Population Geography|5", "Economic Geography|5", "Regional Geography|5",
					"Remote Sensing|5", "Urban Geography|5", "Geography of Tourism|5", "Geopolitics|5",
					"Geographic Field Methods|4", "Hazard and Disaster Geography|5", "Geography of Globalization (Elective)|5", "Capstone Project in Geography|8"),
			entry("Computer Mathematics",
					"Algorithms and Complexity Theory|7", "Numerical Analysis|6", "Discrete Mathematics II|6", "Mathematical Logic|6",
					"Database Systems I for Mathematicians|6", "Operations Research|5", "Cryptographic Mathematics|5", "Computer Graphics Mathematics|5",
					"Mathematical Modeling and Simulation|6", "Computational Geometry|5", "Machine Learning Mathematics|5", "Optimization Theory|5",
					"Coding Theory|4", "Scientific Computing II|5", "Game Theory and Applications (Elective)|5", "Capstone Project in Computer Mathematics|8"),
			entry("Biochemistry",
					"Metabolic Biochemistry|7", "Molecular Biology|6", "Enzymology|6", "Protein Chemistry|6",
					"Analytical Biochemistry|6", "Genetics|5", "Cell Signaling|5", "Biochemical Laboratory Techniques|5",
					"Clinical Biochemistry|6", "Structural Biology|5", "Bioinformatics for Biochemists|5", "Nutritional Biochemistry|5",
					"Pharmaceutical Biochemistry|4", "Immunochemistry|5", "Biotechnology Fundamentals (Elective)|5", "Capstone Project in Biochemistry|8"));

	private static final List<ProgramEntry> ART_PROGRAMS = List.of(
			entry("Graphic Design",
					"Brand Identity Design|7", "Editorial Design|6", "Packaging Design|6", "User Interface Design|6",
					"Motion Graphics|6", "Print Production Techniques|5", "Typography II|5", "Advertising Design|5",
					"User Experience Design|6", "Design for Digital Media|5", "Information Design and Data Visualization|5", "Design Studio Practicum|5",
					"Design Business and Client Management|4", "Illustration for Graphic Design|5", "Generative and AI-Assisted Design (Elective)|5", "Capstone Project in Graphic Design|8"),
			entry("Interior Design",
					"Space Planning|7", "Materials and Finishes for Interiors|6", "Lighting Design|6", "Furniture Design|6",
					"Interior Design Studio I|6", "Building Codes and Accessibility|5", "Computer-Aided Interior Design|5", "Color and Texture in Interior Spaces|5",
					"Interior Design Studio II|6", "Sustainable Interior Design|5", "Commercial Interior Design|5", "Residential Interior Design|5",
					"History of Interior Design|4", "Design Presentation and Visualization|5", "Exhibition and Retail Design (Elective)|5", "Capstone Project in Interior Design|8"),
			entry("Fine Arts",
					"Painting II|7", "Sculpture II|6", "Printmaking|6", "Contemporary Art Practices|6",
					"Art Theory and Criticism|6", "Mixed Media and Installation Art|5", "Figure Drawing|5", "Studio Practice I|5",
					"Painting III|6", "Advanced Sculpture|5", "Curatorial Practice|5", "Public Art and Site-Specific Work|5",
					"Art Exhibition Management|4", "Studio Practice II|5", "Printmaking and Book Arts (Elective)|5", "Capstone Exhibition Project in Fine Arts|8"),
			entry("Fashion Design",
					"Pattern Making|7", "Garment Construction|6", "Textile Science|6", "Fashion Illustration|6",
					"Fashion Design Studio I|6", "Fashion History|5", "Draping Techniques|5", "Computer-Aided Fashion Design|5",
					"Fashion Design Studio II|6", "Sustainable and Ethical Fashion|5", "Fashion Collection Development|5", "Fashion Merchandising|5",
					"Fashion Business and Branding|4", "Costume Design|5", "Knitwear Design (Elective)|5", "Capstone Collection Project in Fashion Design|8"),
			entry("Animation and Game Design",
					"2D Animation|7", "3D Modeling and Animation|6", "Game Design Principles|6", "Character Design|6",
					"Storyboarding and Visual Narrative|6", "Game Engine Development|5", "Rigging and Character Animation|5", "Sound Design for Animation and Games|5",
					"Level Design|6", "Game Programming Fundamentals|5", "Visual Effects|5", "Interactive Narrative Design|5",
					"Game Production Pipeline|4", "Motion Capture and Performance Animation|5", "Virtual and Augmented Reality Design (Elective)|5", "Capstone Project in Animation and Game Design|8"),
			entry("Music",
					"Music Theory III|6", "Harmony and Counterpoint|6", "Music History: Romantic Era|6", "Ensemble Performance|6",
					"Composition Techniques|6", "Conducting Fundamentals|5", "Instrumental or Vocal Performance III|5", "Music Technology and Recording|5",
					"Music History: 20th and 21st Century|5", "Orchestration|5", "Advanced Composition|5", "Music Production and Sound Engineering|5",
					"Music Business and Copyright|4", "Instrumental or Vocal Performance IV|5", "Film Scoring (Elective)|5", "Capstone Recital Project in Music|8"),
			entry("Industrial Design",
					"Product Design Studio I|7", "Ergonomics and Human Factors|6", "Materials and Manufacturing for Designers|6", "3D Modeling for Product Design|6",
					"Design for Sustainability|6", "Rapid Prototyping and 3D Printing|5", "Design Research Methods|5", "Color and Material Design|5",
					"Product Design Studio II|6", "User-Centered Design|5", "Design for Manufacturing and Assembly|5", "Packaging and Product Identity|5",
					"Design Entrepreneurship|4", "Furniture and Home Product Design|5", "Transportation Design (Elective)|5", "Capstone Project in Industrial Design|8"));

	private static final Map<FacultyKey, List<ProgramEntry>> BY_FACULTY = Map.ofEntries(
			Map.entry(FacultyKey.CS, CS_PROGRAMS), Map.entry(FacultyKey.EE, EE_PROGRAMS), Map.entry(FacultyKey.ME, ME_PROGRAMS),
			Map.entry(FacultyKey.CIV, CIV_PROGRAMS), Map.entry(FacultyKey.ECO, ECO_PROGRAMS), Map.entry(FacultyKey.LAW, LAW_PROGRAMS),
			Map.entry(FacultyKey.MED, MED_PROGRAMS), Map.entry(FacultyKey.HUM, HUM_PROGRAMS), Map.entry(FacultyKey.SCI, SCI_PROGRAMS),
			Map.entry(FacultyKey.ART, ART_PROGRAMS));

	public static List<ProgramEntry> forFaculty(FacultyKey key) {
		return BY_FACULTY.get(key);
	}
}
