export enum PermissionEnum{
    ADMINISTRATOR_PERMISSION = 'ADMINISTRATOR_PERMISSION',
    STUDENT_PERMISSION = 'STUDENT_PERMISSION',
    TEACHER_PERMISSION = 'TEACHER_PERMISSION',
    USER_PERMISSION = 'USER_PERMISSION',
    STUDENT_OFFICE_PERMISSION = 'STUDENT_OFFICE_PERMISSION'
}
